<a href="https://colab.research.google.com/github/siddhshekharpandey/desktop-tutorial/blob/main/Customer_Data_Cleaner_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Customer Data Cleaner**

**1.) .IMPORT DATASET**

# **SUMMARY**

 *This project teaches basic data cleaning using tools like Excel or Python (Pandas). It focuses*
*on preparing customer records for analysis.*

In [80]:
import pandas as pd
import numpy as np

In [44]:
!ls

 audi.csv	 Cities1.csv		    sample_data
 car_price.csv	'Customer Call List.xlsx'

In [46]:
df=pd.read_excel("/content/Customer Call List.xlsx")

In [48]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [49]:
df.shape ## Overall content

(21, 8)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 0 to 20
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         15 non-null     int64
 1   First_Name         15 non-null     object
 2   Last_Name          15 non-null     object
 3   Phone_Number       15 non-null     object
 4   Address            15 non-null     object
 5   Paying Customer    15 non-null     object
 6   Do_Not_Contact     15 non-null     object
 7   Not_Useful_Column  15 non-null     bool
dtypes: bool(1), int64(1), object(6)
memory usage: 1.5+ KB

# **Identify and handle missing values**

In [53]:
df.isnull()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,True,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,True,False,False,False,True,False
9,False,False,False,False,False,False,False,False
10,False,False,False,True,False,False,False,False
11,False,False,False,False,False,False,True,False
12,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,True,False
18,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False

In [55]:
df.isnull().sum()

CustomerID           0
First_Name           0
Last_Name            1
Phone_Number         2
Address              0
Paying Customer      0
Do_Not_Contact       4
Not_Useful_Column    0
dtype: int64

## **Filling null values**

In [61]:
df2 =df.fillna(value=0)
df2

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

# **Filling null values with a previous value**

In [62]:
df4=df.fillna(method="pad")
df4

/tmp/ipython-input-3103713598.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df4=df.fillna(method="pad")

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [65]:
df4.isnull().sum()

CustomerID           0
First_Name           0
Last_Name            0
Phone_Number         0
Address              0
Paying Customer      0
Do_Not_Contact       0
Not_Useful_Column    0
dtype: int64

In [66]:
# Filling null values with the next value
df5=df.fillna(method="bfill")
df5

/tmp/ipython-input-692918494.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df5=df.fillna(method="bfill")

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [67]:
df6 = df.fillna(method="pad",axis =1)
df6

/tmp/ipython-input-3992864957.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df6 = df.fillna(method="pad",axis =1)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [68]:
df7 = df.fillna(method="bfill",axis =1)
df7

/tmp/ipython-input-2441577406.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df7 = df.fillna(method="bfill",axis =1)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [70]:
#filling different values in null in different column
df8 = df.fillna({"Last_Name":"Unknown","Phone_Number":"Unknown"})
df8

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [76]:
#filling null values with the mean of the column
df9 = df.fillna(df["CustomerID"].mean())
df9

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [77]:
df10=df.dropna()
df10

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

# **Remove duplicates and fix inconsistent entries**

In [134]:
df11 = df10

# 1. Preview original shape
print("Original rows:", len(df11))

Original rows: 15

In [135]:
# 2. Fix inconsistent entries
#    a) Strip whitespace on all string cells
df11 = df11.applymap(lambda x: x.strip() if isinstance(x, str) else x)

#    b) Standardize casing for key text columns
text_cols = ['First Name', 'Last Name', 'City', 'State']  # adjust as needed
for col in text_cols:
    if col in df.columns:
        df[col] = df[col].str.title()

#    c) Normalize phone numbers to (XXX) XXX-XXXX
def format_phone(x):
    digits = re.sub(r'\D', '', str(x))
    if len(digits) == 10:
        return f"({digits[:3]}) {digits[3:6]}-{digits[6:]}"
    return x

if 'Phone Number' in df11.columns:
    df11['Phone Number'] = df11['Phone Number'].apply(format_phone)

/tmp/ipython-input-243257278.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df11 = df11.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [136]:
# 3. Remove exact duplicate rows
df = df.drop_duplicates()

In [137]:
# 6. Preview cleaned DataFrame
print("Cleaned rows:", len(df))
print(df11.head())

Cleaned rows: 20
   CustomerID First_Name Last_Name  Phone_Number  \
0        1001      Frodo   Baggins  123-545-5421
1        1002       Abed     Nadir  123/643/9775
3        1004     Dwight   Schrute  123-543-2345
4        1005        Jon      Snow  876|678|3469
5        1006        Ron   Swanson  304-762-2467

                                 Address Paying Customer Do_Not_Contact  \
0                  123 Shire Lane, Shire             Yes             No
1                    93 West Main Street              No            Yes
3  980 Paper Avenue, Pennsylvania, 18503             Yes              Y
4                       123 Dragons Road               Y             No
5                       768 City Parkway             Yes            Yes

   Not_Useful_Column
0               True
1              False
3               True
4               True
5               True

# **Format column**

In [141]:
df13 = df11

# 1: Format a date column (e.g. ‘Call Date’)
if 'Call Date' in df13.columns:
    df13['Call Date'] = pd.to_datetime(df13['Call Date']).dt.strftime('%Y-%m-%d')

# 2: Round a numeric column (e.g. ‘Amount Due’) to 2 decimal places
if 'Amount Due' in df13.columns:
    df13['Amount Due'] = df13['Amount Due'].round(2)

# 3: Format phone numbers (e.g. ‘Phone Number’) as (XXX) XXX-XXXX
import re
def format_phone(x):
    digits = re.sub(r'\D', '', str(x))
    if len(digits) == 10:
        return f"({digits[:3]}) {digits[3:6]}-{digits[6:]}"
    return x  # leave it as is if not 10 digits

if 'Phone Number' in df.columns:
    df13['Phone Number'] = df13['Phone Number'].apply(format_phone)

# Preview the result
print(df.head())

   CustomerID First_Name Last_Name  Phone_Number  \
0        1001      Frodo   Baggins  123-545-5421
1        1002       Abed     Nadir  123/643/9775
2        1003     Walter    /White    7066950392
3        1004     Dwight   Schrute  123-543-2345
4        1005        Jon      Snow  876|678|3469

                                 Address Paying Customer Do_Not_Contact  \
0                  123 Shire Lane, Shire             Yes             No
1                    93 West Main Street              No            Yes
2                     298 Drugs Driveway               N            NaN
3  980 Paper Avenue, Pennsylvania, 18503             Yes              Y
4                       123 Dragons Road               Y             No

   Not_Useful_Column
0               True
1              False
2               True
3               True
4               True